FROM golang:latest AS build
WORKDIR /go/src/github.com/triggermesh/aws-kinesis-channel/
ADD . ./
RUN go build -o /go/bin/controller ./cmd/controller/main.go

FROM gcr.io/distroless/base
COPY --from=build /go/bin/controller /
CMD ["/controller"]
