FROM golang:latest AS build
WORKDIR /go/src/github.com/triggermesh/aws-kinesis-channel/
ADD . ./
RUN go build -o /go/bin/dispatcher ./cmd/dispatcher/main.go

FROM gcr.io/distroless/base
COPY --from=build /go/bin/dispatcher /
CMD ["/dispatcher"]
