/*
Copyright (c) 2020 TriggerMesh Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/triggermesh/aws-kinesis-channel/pkg/apis/messaging/v1alpha1"
	scheme "github.com/triggermesh/aws-kinesis-channel/pkg/client/clientset/internalclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KinesisChannelsGetter has a method to return a KinesisChannelInterface.
// A group's client should implement this interface.
type KinesisChannelsGetter interface {
	KinesisChannels(namespace string) KinesisChannelInterface
}

// KinesisChannelInterface has methods to work with KinesisChannel resources.
type KinesisChannelInterface interface {
	Create(*v1alpha1.KinesisChannel) (*v1alpha1.KinesisChannel, error)
	Update(*v1alpha1.KinesisChannel) (*v1alpha1.KinesisChannel, error)
	UpdateStatus(*v1alpha1.KinesisChannel) (*v1alpha1.KinesisChannel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KinesisChannel, error)
	List(opts v1.ListOptions) (*v1alpha1.KinesisChannelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KinesisChannel, err error)
	KinesisChannelExpansion
}

// kinesisChannels implements KinesisChannelInterface
type kinesisChannels struct {
	client rest.Interface
	ns     string
}

// newKinesisChannels returns a KinesisChannels
func newKinesisChannels(c *MessagingV1alpha1Client, namespace string) *kinesisChannels {
	return &kinesisChannels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kinesisChannel, and returns the corresponding kinesisChannel object, and an error if there is any.
func (c *kinesisChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.KinesisChannel, err error) {
	result = &v1alpha1.KinesisChannel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kinesischannels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KinesisChannels that match those selectors.
func (c *kinesisChannels) List(opts v1.ListOptions) (result *v1alpha1.KinesisChannelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KinesisChannelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kinesischannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kinesisChannels.
func (c *kinesisChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kinesischannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a kinesisChannel and creates it.  Returns the server's representation of the kinesisChannel, and an error, if there is any.
func (c *kinesisChannels) Create(kinesisChannel *v1alpha1.KinesisChannel) (result *v1alpha1.KinesisChannel, err error) {
	result = &v1alpha1.KinesisChannel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kinesischannels").
		Body(kinesisChannel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kinesisChannel and updates it. Returns the server's representation of the kinesisChannel, and an error, if there is any.
func (c *kinesisChannels) Update(kinesisChannel *v1alpha1.KinesisChannel) (result *v1alpha1.KinesisChannel, err error) {
	result = &v1alpha1.KinesisChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kinesischannels").
		Name(kinesisChannel.Name).
		Body(kinesisChannel).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *kinesisChannels) UpdateStatus(kinesisChannel *v1alpha1.KinesisChannel) (result *v1alpha1.KinesisChannel, err error) {
	result = &v1alpha1.KinesisChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kinesischannels").
		Name(kinesisChannel.Name).
		SubResource("status").
		Body(kinesisChannel).
		Do().
		Into(result)
	return
}

// Delete takes name of the kinesisChannel and deletes it. Returns an error if one occurs.
func (c *kinesisChannels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kinesischannels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kinesisChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kinesischannels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kinesisChannel.
func (c *kinesisChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KinesisChannel, err error) {
	result = &v1alpha1.KinesisChannel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kinesischannels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
