/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	kinesissourcev1 "github.com/triggermesh/aws-kinesis-provisioner/pkg/apis/kinesissource/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKinesisSources implements KinesisSourceInterface
type FakeKinesisSources struct {
	Fake *FakeKinesissourceV1
	ns   string
}

var kinesissourcesResource = schema.GroupVersionResource{Group: "kinesissource.triggermesh.dev", Version: "v1", Resource: "kinesissources"}

var kinesissourcesKind = schema.GroupVersionKind{Group: "kinesissource.triggermesh.dev", Version: "v1", Kind: "KinesisSource"}

// Get takes name of the kinesisSource, and returns the corresponding kinesisSource object, and an error if there is any.
func (c *FakeKinesisSources) Get(name string, options v1.GetOptions) (result *kinesissourcev1.KinesisSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kinesissourcesResource, c.ns, name), &kinesissourcev1.KinesisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kinesissourcev1.KinesisSource), err
}

// List takes label and field selectors, and returns the list of KinesisSources that match those selectors.
func (c *FakeKinesisSources) List(opts v1.ListOptions) (result *kinesissourcev1.KinesisSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kinesissourcesResource, kinesissourcesKind, c.ns, opts), &kinesissourcev1.KinesisSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &kinesissourcev1.KinesisSourceList{ListMeta: obj.(*kinesissourcev1.KinesisSourceList).ListMeta}
	for _, item := range obj.(*kinesissourcev1.KinesisSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kinesisSources.
func (c *FakeKinesisSources) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kinesissourcesResource, c.ns, opts))

}

// Create takes the representation of a kinesisSource and creates it.  Returns the server's representation of the kinesisSource, and an error, if there is any.
func (c *FakeKinesisSources) Create(kinesisSource *kinesissourcev1.KinesisSource) (result *kinesissourcev1.KinesisSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kinesissourcesResource, c.ns, kinesisSource), &kinesissourcev1.KinesisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kinesissourcev1.KinesisSource), err
}

// Update takes the representation of a kinesisSource and updates it. Returns the server's representation of the kinesisSource, and an error, if there is any.
func (c *FakeKinesisSources) Update(kinesisSource *kinesissourcev1.KinesisSource) (result *kinesissourcev1.KinesisSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kinesissourcesResource, c.ns, kinesisSource), &kinesissourcev1.KinesisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kinesissourcev1.KinesisSource), err
}

// Delete takes name of the kinesisSource and deletes it. Returns an error if one occurs.
func (c *FakeKinesisSources) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kinesissourcesResource, c.ns, name), &kinesissourcev1.KinesisSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKinesisSources) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kinesissourcesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &kinesissourcev1.KinesisSourceList{})
	return err
}

// Patch applies the patch and returns the patched kinesisSource.
func (c *FakeKinesisSources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *kinesissourcev1.KinesisSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kinesissourcesResource, c.ns, name, pt, data, subresources...), &kinesissourcev1.KinesisSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*kinesissourcev1.KinesisSource), err
}
